---
# This docker-compose file is ignoring in production, but been using
# in development with: $ docker-compose up

version: "3.8"
services:
  postgresql-service:
    container_name: ktorapp-postgres-dev
    #network_mode: host
    environment:
      POSTGRES_USER: ktorapp
      POSTGRES_PASSWORD: ktorapp
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - "5432:5432"

  pgadmin4-service:
    image: dpage/pgadmin4
    restart: always
    #network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.pg
      PGADMIN_DEFAULT_PASSWORD: pg
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgresql-service
